# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.15.0

pipelines:
  default:
    - step:
        deployment: TEST
        name: Deploy to test
        image: atlassian/default-image:2
        script:
          - "npm install -g @angular/cli"
          - "npm install --quiet"
          - "ng build --configuration=test"
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www/dev.onriot.net'
              LOCAL_PATH: 'build/*'
              DEBUG: 'true'

    - step:
        deployment: PROD
        name: Deploy to all prod servers
        trigger: manual
        image: atlassian/default-image:2
        script:
          - "npm install -g @angular/cli"
          - "npm install --quiet"
          - "ng build --configuration=production"
          - pipe: atlassian/sftp-deploy:0.5.2
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_HOST
              REMOTE_PATH: '/var/www/www.onriot.net'
              LOCAL_PATH: 'build/*'
              DEBUG: 'true'
